### ISSUE TITLE
Integrate CI builds

### ISSUE THREAD

**Issue by karnkaul** [tccppgg/rect#16]
Appveyor:
- Windows and Linux
- super straightforward to setup
- trigger builds without pushing commits
- slowest

Travis:
- Linux only
- PITA to setup
- trigger builds without pushing commits
- fastest

GitHub:
- Linux only
- PITA to setup
- cannot trigger builds without pushes

@tccppgg/rect-devs please vote!

**Comment by NotAPenguin0** [comment]
+1 for appveyor here

**Comment by alexdevteam** [comment]
I've only tried Azure Devops so far, so I can't really vote on this. +1 for appveyor if azure is out of the question
Azure Devops:
- Windows, Linux and MacOS
- Sucks to set up
- trigger builds without pushing commits
- Relatively fast (Compiled arpiyi for Windows+Linux in around 6m)
- Can also automatize releases and changelogs

**Comment by karnkaul** [comment]
> I've only tried Azure Devops so far, so I can't really vote on this. +1 for appveyor if azure is out of the question
👍 

> * Sucks to set up
Shame, would have been nice to explore

> * Can also automatize releases and changelogs
Appveyor can as well, I deploy `locc` through it.

**Comment by alexdevteam** [comment]
Done

**Comment by karnkaul** [comment]
This isn't complete.

**Comment by alexdevteam** [comment]
ok but #30
