### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by alexdevteam** [tccppgg/rect#23]
The config.yml file should be located outside of any data folders, in the same directory as the executable.

The item I am thinking of is `- extension: <path>`, which indicates a data folder. When loading from a path, that path should be checked for every extension until a file match is found.
For example, if we have the following folders:
```
data/
  startup.yml
  test/
    test.png
dlc/
  test/
    test.png
  dlc/
    icon.png
```
And the config.yml file looks like this:
```yml
- extension: "dlc/"
# Notice that the dlc folder is placed BEFORE the data one, this gives it priority for overrides
- extension: "data/"
```
, the following should happen in the API:
```cpp
// Tries to find startup.yml in dlc, fails, tries it in data and returns data/startup.yml
load("startup.yml");

// Tries to find it first in dlc, so returns dlc/test/test.png, effectively overriding the data pack
load("test/test.png");

// Finds it in dlc and returns dlc/dlc/icon.png
load("dlc/icon.png");
```
This overriding feature allows for changing assets without actually modifying the data folders themselves, just a single line in config.yml. This could allow for texture repaints, debug utils and even translation packs (if we add them at some point).

This is probably similar or equal to the PATH idea karnage suggested, just including integration with config.yml.

This is a draft/idea. Please, before implementing this, comment with any feedback you may have. Mentioning @karnkaul & @jazzfool because they haven't seen the discord convo.

**Comment by NotAPenguin0** [comment]
The best thing is that the overriding system is already implemented because of the way the yml parsing and content manager are set up. If we end up doing this I'll implement it soon.

**Comment by karnkaul** [comment]
Sounds good, my only feedback is that `extension` seems a bit confusing, perhaps we should call it `mount_path` or `datastore` or something else that's not ambiguous.

**Comment by alexdevteam** [comment]
Maybe `datapath`?
